### ISSUE TITLE
1

### ISSUE THREAD

**Issue by VasilyevAA** [Pir-4/WertTestTask#1]
https://github.com/Pir-4/WertTestTask/blob/ee4d7075772ddfad6df66c3532758929f3843064/tests/test_rest_earth.py#L8-L15

Не очень хорошее решение, посмотри как это более классическим способом решается с помощью функционала pytest(либо можешь не привязываться к пайтесту, в общем гораздо более элегантных и правильных решений есть еще 3-4 :) ). Условно, представь, что у тебя есть десяток файлов, где используется эта апишка

**Comment by Pir-4** [comment]
@VasilyevAA 
Thanks. I replaced the global value to a fixture.
